CONSOLE_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = yes
NKRO_ENABLE = yes
RGB_MATRIX_ENABLE = yes

AUDIO_ENABLE = no          # Audio output
BACKLIGHT_ENABLE = no
COMMAND_ENABLE = no
KEY_LOCK_ENABLE = no
MUSIC_ENABLE = no
RGBLIGHT_ENABLE = no       # Enable keyboard RGB underglow
SPACE_CADET_ENABLE = no
SWAP_HANDS_ENABLE = no
# OLED_DRIVER = ssd1306

#Custom Features
CASEMODE_ENABLE = no
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
CUSTOM_LEADER_ENABLE = yes
CUSTOM_SHIFT_ENABLE = no
CUSTOM_SPLIT_TRANSPORT_SYNC = no
DYNAMIC_TAPPING_TERM_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
EXTRAKEY_ENABLE = yes # Audio control and System control
GQT_ENABLE = no
TAP_FLOW_ENABLE = no
KEYCODE_STRING_ENABLE = yes
LAYER_LOCK_ENABLE = yes
MACRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
QT_ENABLE = no
RAW_ENABLE = no
RGB_MATRIX_CUSTOM = yes
SECRETS_ENABLE = yes
SELECT_WORD_ENABLE = yes
SHORTCUTS_ENABLE = yes
SMART_THUMB_KEYS_ENABLE = yes
SPLIT_KEYBOARD = no
TAP_DANCE_ENABLE = yes
TAPHOLD_ENABLE = yes
WINDOW_SWAPPER_ENABLE = yes
REPEAT_KEY_ENABLE = yes

ifdef HLC_TFT_DISPLAY
	QMENU_ENABLE = yes
	DYNAMIC_BACKLIGHT_BLINK = no
endif

ACHORDION_ENABLE = no
CAPITALIZE_KEY_ENABLE = no
CAPSLOCK_TIMER_ENABLE = no
CAPSWORD_ENABLE = no
CUSTOM_ONESHOT_MODS_ENABLE = no
DEFAULT_MOD_KEY_ENABLE = no
EOS_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
LEADER_ENABLE = no
LTO_ENABLE = no
OLED_ENABLE = no
OLED_FONT_ENABLE = no
OLED_MENU_ENABLE = no
OS_TOGGLE_ENABLE = no
SMART_CASE_ENABLE = no
