// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | mono2
//    output | images
//    input  | apple-glyph.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_apple_glyph_length;
extern const uint8_t  gfx_apple_glyph[328];

extern const uint32_t gfx_linux_glyph_length;
extern const uint8_t  gfx_linux_glyph[361];

extern const uint32_t gfx_windows_glyph_length;
extern const uint8_t  gfx_windows_glyph[240];

extern const uint32_t gfx_command_glyph_length;
extern const uint8_t  gfx_command_glyph[146];

extern const uint32_t gfx_ctrl_glyph_length;
extern const uint8_t  gfx_ctrl_glyph[104];

extern const uint32_t gfx_option_glyph_length;
extern const uint8_t  gfx_option_glyph[110];

extern const uint32_t gfx_shift_glyph_length;
extern const uint8_t  gfx_shift_glyph[146];

extern const uint32_t gfx_capslock_length;
extern const uint8_t  gfx_capslock[233];

extern const uint32_t gfx_capsword_length;
extern const uint8_t  gfx_capsword[233];

extern const uint32_t gfx_xcase_length;
extern const uint8_t  gfx_xcase[233];

extern const uint32_t gfx_layer_border_length;
extern const uint8_t  gfx_layer_border[159];

extern const uint32_t gfx_circle_x_length;
extern const uint8_t  gfx_circle_x[361];
