// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | mono2
//    output | images
//    input  | layer_border.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_layer_border_length;
extern const uint8_t  gfx_layer_border[159];
